sonar.projectKey=sonar-demo-ci-cd
sonar.projectName=sonar-demo-ci-cd
sonar.host.url=http://ec2-100-24-204-76.compute-1.amazonaws.com:9000
sonar.login=sqp_0460be27cfa74d68469b2bf4eedb2b9dfbb03133
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,build/**,sonar-project.properties
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# sonar-scanner -Dsonar.branch.name=develop -Dsonar.token=sqp_0460be27cfa74d68469b2bf4eedb2b9dfbb03133
